### ISSUE TITLE
Question: Install all in Docker?

### ISSUE THREAD

**Issue by Yafei777** [jupyter-incubator/dashboards_setup#14]
Hi, all
It's a stupid question maybe, but I hope someone can do me a favor.
I just want to publish a interactive map with Folium in Jupyter notebook to dashboards server. Should I install Jupyter Notebook, Dashboards, Bundler, Server in a Docker in my remote server?
Thanks!

Yafei

**Comment by jhpedemonte** [comment]
If you just want to have a user view the map in the dashboards server, then all you need is (1) the dashboards server and (2) the kernel gateway (with kernel). In this scenario, you could edit the map notebook on your local computer (with Jupyter installed), then upload the file to the dashboards server, or use the bundler to save and upload a ZIP file. Make sense?

**Comment by Yafei777** [comment]
@jhpedemonte It works! Thank you!
